default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  
development:
  <<: *default
  database: smart_garbage_development
  
test:
  <<: *default
  database: smart_garbage_test
  
production:
  url: <%= ENV["DATABASE_URL"] %>
